version: "3"

services:
   influxdb_log:
      image: hypriot/rpi-influxdb
      ports: 
         - "8086:8086"
      container_name: influxdb
      restart: always
      environment:
         - INFLUXDB_INIT_PWD= "admin"
         - PRE_CREATE_DB= iot
      volumes:
         - ./data_store:/var/lib/influxdb
      networks:
         dial:
            ipv4_address: 172.18.0.2


   grafana_log:
      image: grafana/grafana
      ports: 
         - "3000:3000"
      container_name: grafana
      restart: always
      volumes:
         - grafana-db:/var/lib/grafana
         - grafana-log:/var/log/grafana
         - grafana-conf:/etc/grafana
      environment:
         - GF_AUTH_DISABLE_LOGIN_FORM=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
         - GF_SECURITY_ALLOW_EMBEDDING=true

      networks:
          dial:
             ipv4_address: 172.18.0.3
             
      depends_on:
           - influxdb_log
           - mysql_log


   mosquitto_log:
       image: pascaldevink/rpi-mosquitto
       ports:
          - "1883:1883"
       container_name: mosquitto
       restart: always
       volumes:
           - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
           - ./mosquitto/data:/mosquitto/data
           - ./mosquitto/log:/mosquitto/log
       networks:
            dial:
               ipv4_address: 172.18.0.4

         
   mysql_log:
      image: hypriot/rpi-mysql
      ports:
        - "3306:3306"
      container_name: mysql_logistics
      volumes:
         - ./data_store_sql:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=admin        
      networks:
         dial:
           ipv4_address: 172.18.0.5
                
      depends_on:
        - mosquitto_log



networks:
     dial:
        ipam:
          config:
             - subnet: 172.18.0.0/16

volumes:
     grafana-db:
        driver: local
     grafana-log:
        driver: local
     grafana-conf:
        driver: local
